[book]
title = "Book of Lux"
description = "By MTLG Group inspired with mdbook."
authors = ["Dr. Thesmos Prime", "Thesmos Lukas", "Mathrew Tyson", "Lucathar"]
src = "src"
language = "en"
text-direction = "ltr"

[rust]
edition = "2021"

[output.html]
smart-punctuation = true
site-url = "/notebook/"
git-repository-url = "https://github.com/luxbook/notebook"
edit-url-template = "https://github.com/luxbook/notebook/tree/main/"
hash-files = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[build]
build-dir = "book"
create-missing = true

